title: Furqon Surya Kusuma # your name (or website title) here
logo: "https://user-images.githubusercontent.com/113487307/190850131-35f06a39-40d4-4596-8dfe-cbf97daf5edb.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Education
  <br><br>
  Experience 
  <br><br>
  <a href="https://www.linkedin.com/in/furqonsuryakusuma/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
